export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const COMENZAR_INICIO_SESION = 'COMENZAR_INICIO_SESION';
export const CERRAR_SESION = 'CERRAR_SESION';

export const OBTENER_CUARTELES = 'OBTENER_CUARTELES';